source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'AMKCrashProtector_Example' do
    pod 'AMKCrashProtector', :path => '../', :subspecs => [
      'UnrecognizedSelectorProtector',
      'NSKeyValueCodingProtector',
      'MPMoviePlayerViewControllerProtector',
    ]

    target 'AMKCrashProtector_Tests' do
        inherit! :search_paths
    end
end
