source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'AMKCrashProtector_Example' do
    pod 'AMKCrashProtector/Protector', :path => '../'
    pod 'AMKCrashProtector/UnrecognizedSelectorProtector', :path => '../'
    pod 'AMKCrashProtector/NSKeyValueCodingProtector', :path => '../'

    target 'AMKCrashProtector_Tests' do
        inherit! :search_paths
    end
end
